package cn.sotou.dao.model;

// Generated 2014-1-18 16:47:29 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvestItem generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "investItem", catalog = "sotou_test_db")
public class InvestItem implements java.io.Serializable {

	private InvestItemId id;
	private String sourcesitecn;
	private String name;
	private double totalmoney;
	private double process;
	private double rate;
	private String rateaddtion;
	private double award;
	private long duration;
	private int score;
	private String staketype;
	private String stakestate;
	private String ensuretype;
	private String waytorepay;
	private String waytospendmoney;
	private long endtime;
	private double maxinvestnum;
	private double averageinvestnum;
	private int investpeoplenum;
	private int timestodelay;
	private int predictprofit;
	private int moneywaittorepay;
	private String borrowereducation;
	private int borrowermonthincome;
	private int borroweryearincome;
	private String link;
	private String reachlink;
	private Date inserttime;

	public InvestItem() {
	}

	public InvestItem(InvestItemId id, String sourcesitecn, String name,
			double totalmoney, double process, double rate, String rateaddtion,
			double award, long duration, int score, String staketype,
			String stakestate, String ensuretype, String waytorepay,
			String waytospendmoney, long endtime, double maxinvestnum,
			double averageinvestnum, int investpeoplenum, int timestodelay,
			int predictprofit, int moneywaittorepay, String borrowereducation,
			int borrowermonthincome, int borroweryearincome, String link,
			String reachlink, Date inserttime) {
		this.id = id;
		this.sourcesitecn = sourcesitecn;
		this.name = name;
		this.totalmoney = totalmoney;
		this.process = process;
		this.rate = rate;
		this.rateaddtion = rateaddtion;
		this.award = award;
		this.duration = duration;
		this.score = score;
		this.staketype = staketype;
		this.stakestate = stakestate;
		this.ensuretype = ensuretype;
		this.waytorepay = waytorepay;
		this.waytospendmoney = waytospendmoney;
		this.endtime = endtime;
		this.maxinvestnum = maxinvestnum;
		this.averageinvestnum = averageinvestnum;
		this.investpeoplenum = investpeoplenum;
		this.timestodelay = timestodelay;
		this.predictprofit = predictprofit;
		this.moneywaittorepay = moneywaittorepay;
		this.borrowereducation = borrowereducation;
		this.borrowermonthincome = borrowermonthincome;
		this.borroweryearincome = borroweryearincome;
		this.link = link;
		this.reachlink = reachlink;
		this.inserttime = inserttime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "loanid", column = @Column(name = "loanid", nullable = false, length = 128)),
			@AttributeOverride(name = "sourcesiteen", column = @Column(name = "sourcesiteen", nullable = false, length = 64)),
			@AttributeOverride(name = "projecttype", column = @Column(name = "projecttype", nullable = false)) })
	public InvestItemId getId() {
		return this.id;
	}

	public void setId(InvestItemId id) {
		this.id = id;
	}

	@Column(name = "sourcesitecn", nullable = false, length = 64)
	public String getSourcesitecn() {
		return this.sourcesitecn;
	}

	public void setSourcesitecn(String sourcesitecn) {
		this.sourcesitecn = sourcesitecn;
	}

	@Column(name = "name", nullable = false, length = 512)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "totalmoney", nullable = false, precision = 22, scale = 0)
	public double getTotalmoney() {
		return this.totalmoney;
	}

	public void setTotalmoney(double totalmoney) {
		this.totalmoney = totalmoney;
	}

	@Column(name = "process", nullable = false, precision = 22, scale = 0)
	public double getProcess() {
		return this.process;
	}

	public void setProcess(double process) {
		this.process = process;
	}

	@Column(name = "rate", nullable = false, precision = 22, scale = 0)
	public double getRate() {
		return this.rate;
	}

	public void setRate(double rate) {
		this.rate = rate;
	}

	@Column(name = "rateaddtion", nullable = false, length = 1024)
	public String getRateaddtion() {
		return this.rateaddtion;
	}

	public void setRateaddtion(String rateaddtion) {
		this.rateaddtion = rateaddtion;
	}

	@Column(name = "award", nullable = false, precision = 22, scale = 0)
	public double getAward() {
		return this.award;
	}

	public void setAward(double award) {
		this.award = award;
	}

	@Column(name = "duration", nullable = false)
	public long getDuration() {
		return this.duration;
	}

	public void setDuration(long duration) {
		this.duration = duration;
	}

	@Column(name = "score", nullable = false)
	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	@Column(name = "staketype", nullable = false, length = 512)
	public String getStaketype() {
		return this.staketype;
	}

	public void setStaketype(String staketype) {
		this.staketype = staketype;
	}

	@Column(name = "stakestate", nullable = false, length = 512)
	public String getStakestate() {
		return this.stakestate;
	}

	public void setStakestate(String stakestate) {
		this.stakestate = stakestate;
	}

	@Column(name = "ensuretype", nullable = false, length = 512)
	public String getEnsuretype() {
		return this.ensuretype;
	}

	public void setEnsuretype(String ensuretype) {
		this.ensuretype = ensuretype;
	}

	@Column(name = "waytorepay", nullable = false, length = 512)
	public String getWaytorepay() {
		return this.waytorepay;
	}

	public void setWaytorepay(String waytorepay) {
		this.waytorepay = waytorepay;
	}

	@Column(name = "waytospendmoney", nullable = false, length = 2048)
	public String getWaytospendmoney() {
		return this.waytospendmoney;
	}

	public void setWaytospendmoney(String waytospendmoney) {
		this.waytospendmoney = waytospendmoney;
	}

	@Column(name = "endtime", nullable = false)
	public long getEndtime() {
		return this.endtime;
	}

	public void setEndtime(long endtime) {
		this.endtime = endtime;
	}

	@Column(name = "maxinvestnum", nullable = false, precision = 22, scale = 0)
	public double getMaxinvestnum() {
		return this.maxinvestnum;
	}

	public void setMaxinvestnum(double maxinvestnum) {
		this.maxinvestnum = maxinvestnum;
	}

	@Column(name = "averageinvestnum", nullable = false, precision = 22, scale = 0)
	public double getAverageinvestnum() {
		return this.averageinvestnum;
	}

	public void setAverageinvestnum(double averageinvestnum) {
		this.averageinvestnum = averageinvestnum;
	}

	@Column(name = "investpeoplenum", nullable = false)
	public int getInvestpeoplenum() {
		return this.investpeoplenum;
	}

	public void setInvestpeoplenum(int investpeoplenum) {
		this.investpeoplenum = investpeoplenum;
	}

	@Column(name = "timestodelay", nullable = false)
	public int getTimestodelay() {
		return this.timestodelay;
	}

	public void setTimestodelay(int timestodelay) {
		this.timestodelay = timestodelay;
	}

	@Column(name = "predictprofit", nullable = false)
	public int getPredictprofit() {
		return this.predictprofit;
	}

	public void setPredictprofit(int predictprofit) {
		this.predictprofit = predictprofit;
	}

	@Column(name = "moneywaittorepay", nullable = false)
	public int getMoneywaittorepay() {
		return this.moneywaittorepay;
	}

	public void setMoneywaittorepay(int moneywaittorepay) {
		this.moneywaittorepay = moneywaittorepay;
	}

	@Column(name = "borrowereducation", nullable = false, length = 512)
	public String getBorrowereducation() {
		return this.borrowereducation;
	}

	public void setBorrowereducation(String borrowereducation) {
		this.borrowereducation = borrowereducation;
	}

	@Column(name = "borrowermonthincome", nullable = false)
	public int getBorrowermonthincome() {
		return this.borrowermonthincome;
	}

	public void setBorrowermonthincome(int borrowermonthincome) {
		this.borrowermonthincome = borrowermonthincome;
	}

	@Column(name = "borroweryearincome", nullable = false)
	public int getBorroweryearincome() {
		return this.borroweryearincome;
	}

	public void setBorroweryearincome(int borroweryearincome) {
		this.borroweryearincome = borroweryearincome;
	}

	@Column(name = "link", nullable = false, length = 512)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "reachlink", nullable = false, length = 512)
	public String getReachlink() {
		return this.reachlink;
	}

	public void setReachlink(String reachlink) {
		this.reachlink = reachlink;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "inserttime", nullable = false, length = 19)
	public Date getInserttime() {
		return this.inserttime;
	}

	public void setInserttime(Date inserttime) {
		this.inserttime = inserttime;
	}

}
