package cn.sotou.dao.model;

// Generated Jan 22, 2014 4:42:30 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ListOldId generated by hbm2java
 */
@Embeddable
public class ListOldId implements java.io.Serializable {

	private String sourcesiteen;
	private String sourcesitecn;
	private String url;
	private String reachurl;
	private String projecttype;
	private String loanid;

	public ListOldId() {
	}

	public ListOldId(String sourcesiteen, String sourcesitecn, String url,
			String reachurl, String projecttype, String loanid) {
		this.sourcesiteen = sourcesiteen;
		this.sourcesitecn = sourcesitecn;
		this.url = url;
		this.reachurl = reachurl;
		this.projecttype = projecttype;
		this.loanid = loanid;
	}

	@Column(name = "sourcesiteen", nullable = false, length = 64)
	public String getSourcesiteen() {
		return this.sourcesiteen;
	}

	public void setSourcesiteen(String sourcesiteen) {
		this.sourcesiteen = sourcesiteen;
	}

	@Column(name = "sourcesitecn", nullable = false, length = 64)
	public String getSourcesitecn() {
		return this.sourcesitecn;
	}

	public void setSourcesitecn(String sourcesitecn) {
		this.sourcesitecn = sourcesitecn;
	}

	@Column(name = "url", nullable = false, length = 512)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "reachurl", nullable = false, length = 512)
	public String getReachurl() {
		return this.reachurl;
	}

	public void setReachurl(String reachurl) {
		this.reachurl = reachurl;
	}

	@Column(name = "projecttype", nullable = false, length = 512)
	public String getProjecttype() {
		return this.projecttype;
	}

	public void setProjecttype(String projecttype) {
		this.projecttype = projecttype;
	}

	@Column(name = "loanid", nullable = false, length = 512)
	public String getLoanid() {
		return this.loanid;
	}

	public void setLoanid(String loanid) {
		this.loanid = loanid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ListOldId))
			return false;
		ListOldId castOther = (ListOldId) other;

		return ((this.getSourcesiteen() == castOther.getSourcesiteen()) || (this
				.getSourcesiteen() != null
				&& castOther.getSourcesiteen() != null && this
				.getSourcesiteen().equals(castOther.getSourcesiteen())))
				&& ((this.getSourcesitecn() == castOther.getSourcesitecn()) || (this
						.getSourcesitecn() != null
						&& castOther.getSourcesitecn() != null && this
						.getSourcesitecn().equals(castOther.getSourcesitecn())))
				&& ((this.getUrl() == castOther.getUrl()) || (this.getUrl() != null
						&& castOther.getUrl() != null && this.getUrl().equals(
						castOther.getUrl())))
				&& ((this.getReachurl() == castOther.getReachurl()) || (this
						.getReachurl() != null
						&& castOther.getReachurl() != null && this
						.getReachurl().equals(castOther.getReachurl())))
				&& ((this.getProjecttype() == castOther.getProjecttype()) || (this
						.getProjecttype() != null
						&& castOther.getProjecttype() != null && this
						.getProjecttype().equals(castOther.getProjecttype())))
				&& ((this.getLoanid() == castOther.getLoanid()) || (this
						.getLoanid() != null && castOther.getLoanid() != null && this
						.getLoanid().equals(castOther.getLoanid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getSourcesiteen() == null ? 0 : this.getSourcesiteen()
						.hashCode());
		result = 37
				* result
				+ (getSourcesitecn() == null ? 0 : this.getSourcesitecn()
						.hashCode());
		result = 37 * result
				+ (getUrl() == null ? 0 : this.getUrl().hashCode());
		result = 37 * result
				+ (getReachurl() == null ? 0 : this.getReachurl().hashCode());
		result = 37
				* result
				+ (getProjecttype() == null ? 0 : this.getProjecttype()
						.hashCode());
		result = 37 * result
				+ (getLoanid() == null ? 0 : this.getLoanid().hashCode());
		return result;
	}

}
