package cn.sotou.dao.model;

// Generated 2014-2-25 20:52:59 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductsTouzi generated by hbm2java
 */
@Entity
@Table(name = "products_touzi", catalog = "sotou")
public class ProductsTouzi implements java.io.Serializable {

	private Long id;
	private long sourcesiteid;
	private int projecttype;
	private String loanid;
	private String name;
	private double totalmoney;
	private double process;
	private double yearprofitrate;
	private String rateaddtion;
	private double award;
	private double duration;
	private int score;
	private int staketype;
	private String stakestate;
	private int ensuretype;
	private int waytorepay;
	private String waytospendmoney;
	private long endtime;
	private double maxinvestnum;
	private double averageinvestnum;
	private int investpeoplenum;
	private int timestodelay;
	private int predictprofit;
	private int moneywaittorepay;
	private String borrowereducation;
	private double borrowermonthincome;
	private double borroweryearincome;
	private String link;
	private String reachlink;
	private Date inserttime;
	private Set comments = new HashSet(0);

	public ProductsTouzi() {
	}

	public ProductsTouzi(long sourcesiteid, int projecttype, String loanid,
			String name, double totalmoney, double process,
			double yearprofitrate, String rateaddtion, double award,
			double duration, int score, int staketype, String stakestate,
			int ensuretype, int waytorepay, String waytospendmoney,
			long endtime, double maxinvestnum, double averageinvestnum,
			int investpeoplenum, int timestodelay, int predictprofit,
			int moneywaittorepay, String borrowereducation,
			double borrowermonthincome, double borroweryearincome, String link,
			String reachlink, Date inserttime) {
		this.sourcesiteid = sourcesiteid;
		this.projecttype = projecttype;
		this.loanid = loanid;
		this.name = name;
		this.totalmoney = totalmoney;
		this.process = process;
		this.yearprofitrate = yearprofitrate;
		this.rateaddtion = rateaddtion;
		this.award = award;
		this.duration = duration;
		this.score = score;
		this.staketype = staketype;
		this.stakestate = stakestate;
		this.ensuretype = ensuretype;
		this.waytorepay = waytorepay;
		this.waytospendmoney = waytospendmoney;
		this.endtime = endtime;
		this.maxinvestnum = maxinvestnum;
		this.averageinvestnum = averageinvestnum;
		this.investpeoplenum = investpeoplenum;
		this.timestodelay = timestodelay;
		this.predictprofit = predictprofit;
		this.moneywaittorepay = moneywaittorepay;
		this.borrowereducation = borrowereducation;
		this.borrowermonthincome = borrowermonthincome;
		this.borroweryearincome = borroweryearincome;
		this.link = link;
		this.reachlink = reachlink;
		this.inserttime = inserttime;
	}

	public ProductsTouzi(long sourcesiteid, int projecttype, String loanid,
			String name, double totalmoney, double process,
			double yearprofitrate, String rateaddtion, double award,
			double duration, int score, int staketype, String stakestate,
			int ensuretype, int waytorepay, String waytospendmoney,
			long endtime, double maxinvestnum, double averageinvestnum,
			int investpeoplenum, int timestodelay, int predictprofit,
			int moneywaittorepay, String borrowereducation,
			double borrowermonthincome, double borroweryearincome, String link,
			String reachlink, Date inserttime, Set comments) {
		this.sourcesiteid = sourcesiteid;
		this.projecttype = projecttype;
		this.loanid = loanid;
		this.name = name;
		this.totalmoney = totalmoney;
		this.process = process;
		this.yearprofitrate = yearprofitrate;
		this.rateaddtion = rateaddtion;
		this.award = award;
		this.duration = duration;
		this.score = score;
		this.staketype = staketype;
		this.stakestate = stakestate;
		this.ensuretype = ensuretype;
		this.waytorepay = waytorepay;
		this.waytospendmoney = waytospendmoney;
		this.endtime = endtime;
		this.maxinvestnum = maxinvestnum;
		this.averageinvestnum = averageinvestnum;
		this.investpeoplenum = investpeoplenum;
		this.timestodelay = timestodelay;
		this.predictprofit = predictprofit;
		this.moneywaittorepay = moneywaittorepay;
		this.borrowereducation = borrowereducation;
		this.borrowermonthincome = borrowermonthincome;
		this.borroweryearincome = borroweryearincome;
		this.link = link;
		this.reachlink = reachlink;
		this.inserttime = inserttime;
		this.comments = comments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "sourcesiteid", nullable = false)
	public long getSourcesiteid() {
		return this.sourcesiteid;
	}

	public void setSourcesiteid(long sourcesiteid) {
		this.sourcesiteid = sourcesiteid;
	}

	@Column(name = "projecttype", nullable = false)
	public int getProjecttype() {
		return this.projecttype;
	}

	public void setProjecttype(int projecttype) {
		this.projecttype = projecttype;
	}

	@Column(name = "loanid", nullable = false, length = 128)
	public String getLoanid() {
		return this.loanid;
	}

	public void setLoanid(String loanid) {
		this.loanid = loanid;
	}

	@Column(name = "name", nullable = false, length = 512)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "totalmoney", nullable = false, precision = 22, scale = 0)
	public double getTotalmoney() {
		return this.totalmoney;
	}

	public void setTotalmoney(double totalmoney) {
		this.totalmoney = totalmoney;
	}

	@Column(name = "process", nullable = false, precision = 22, scale = 0)
	public double getProcess() {
		return this.process;
	}

	public void setProcess(double process) {
		this.process = process;
	}

	@Column(name = "yearprofitrate", nullable = false, precision = 22, scale = 0)
	public double getYearprofitrate() {
		return this.yearprofitrate;
	}

	public void setYearprofitrate(double yearprofitrate) {
		this.yearprofitrate = yearprofitrate;
	}

	@Column(name = "rateaddtion", nullable = false, length = 1024)
	public String getRateaddtion() {
		return this.rateaddtion;
	}

	public void setRateaddtion(String rateaddtion) {
		this.rateaddtion = rateaddtion;
	}

	@Column(name = "award", nullable = false, precision = 22, scale = 0)
	public double getAward() {
		return this.award;
	}

	public void setAward(double award) {
		this.award = award;
	}

	@Column(name = "duration", nullable = false, precision = 22, scale = 0)
	public double getDuration() {
		return this.duration;
	}

	public void setDuration(double duration) {
		this.duration = duration;
	}

	@Column(name = "score", nullable = false)
	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	@Column(name = "staketype", nullable = false)
	public int getStaketype() {
		return this.staketype;
	}

	public void setStaketype(int staketype) {
		this.staketype = staketype;
	}

	@Column(name = "stakestate", nullable = false, length = 512)
	public String getStakestate() {
		return this.stakestate;
	}

	public void setStakestate(String stakestate) {
		this.stakestate = stakestate;
	}

	@Column(name = "ensuretype", nullable = false)
	public int getEnsuretype() {
		return this.ensuretype;
	}

	public void setEnsuretype(int ensuretype) {
		this.ensuretype = ensuretype;
	}

	@Column(name = "waytorepay", nullable = false)
	public int getWaytorepay() {
		return this.waytorepay;
	}

	public void setWaytorepay(int waytorepay) {
		this.waytorepay = waytorepay;
	}

	@Column(name = "waytospendmoney", nullable = false, length = 2048)
	public String getWaytospendmoney() {
		return this.waytospendmoney;
	}

	public void setWaytospendmoney(String waytospendmoney) {
		this.waytospendmoney = waytospendmoney;
	}

	@Column(name = "endtime", nullable = false)
	public long getEndtime() {
		return this.endtime;
	}

	public void setEndtime(long endtime) {
		this.endtime = endtime;
	}

	@Column(name = "maxinvestnum", nullable = false, precision = 22, scale = 0)
	public double getMaxinvestnum() {
		return this.maxinvestnum;
	}

	public void setMaxinvestnum(double maxinvestnum) {
		this.maxinvestnum = maxinvestnum;
	}

	@Column(name = "averageinvestnum", nullable = false, precision = 22, scale = 0)
	public double getAverageinvestnum() {
		return this.averageinvestnum;
	}

	public void setAverageinvestnum(double averageinvestnum) {
		this.averageinvestnum = averageinvestnum;
	}

	@Column(name = "investpeoplenum", nullable = false)
	public int getInvestpeoplenum() {
		return this.investpeoplenum;
	}

	public void setInvestpeoplenum(int investpeoplenum) {
		this.investpeoplenum = investpeoplenum;
	}

	@Column(name = "timestodelay", nullable = false)
	public int getTimestodelay() {
		return this.timestodelay;
	}

	public void setTimestodelay(int timestodelay) {
		this.timestodelay = timestodelay;
	}

	@Column(name = "predictprofit", nullable = false)
	public int getPredictprofit() {
		return this.predictprofit;
	}

	public void setPredictprofit(int predictprofit) {
		this.predictprofit = predictprofit;
	}

	@Column(name = "moneywaittorepay", nullable = false)
	public int getMoneywaittorepay() {
		return this.moneywaittorepay;
	}

	public void setMoneywaittorepay(int moneywaittorepay) {
		this.moneywaittorepay = moneywaittorepay;
	}

	@Column(name = "borrowereducation", nullable = false, length = 512)
	public String getBorrowereducation() {
		return this.borrowereducation;
	}

	public void setBorrowereducation(String borrowereducation) {
		this.borrowereducation = borrowereducation;
	}

	@Column(name = "borrowermonthincome", nullable = false, precision = 22, scale = 0)
	public double getBorrowermonthincome() {
		return this.borrowermonthincome;
	}

	public void setBorrowermonthincome(double borrowermonthincome) {
		this.borrowermonthincome = borrowermonthincome;
	}

	@Column(name = "borroweryearincome", nullable = false, precision = 22, scale = 0)
	public double getBorroweryearincome() {
		return this.borroweryearincome;
	}

	public void setBorroweryearincome(double borroweryearincome) {
		this.borroweryearincome = borroweryearincome;
	}

	@Column(name = "link", nullable = false, length = 512)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "reachlink", nullable = false, length = 512)
	public String getReachlink() {
		return this.reachlink;
	}

	public void setReachlink(String reachlink) {
		this.reachlink = reachlink;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "inserttime", nullable = false, length = 19)
	public Date getInserttime() {
		return this.inserttime;
	}

	public void setInserttime(Date inserttime) {
		this.inserttime = inserttime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productsTouzi")
	public Set getComments() {
		return this.comments;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

}
