package cn.sotou.dao.model;

// Generated Jan 22, 2014 4:42:30 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RepayType generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "repay_type", catalog = "dbtest")
public class RepayType implements java.io.Serializable {

	private Integer id;
	private String type;

	public RepayType() {
	}

	public RepayType(String type) {
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false, length = 512)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
