package cn.sotou.dao.model;

// Generated 2014-2-25 20:52:59 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SocialRelationId generated by hbm2java
 */
@Embeddable
public class SocialRelationId implements java.io.Serializable {

	private int loginInfoId;
	private int socialLoginTypeId;

	public SocialRelationId() {
	}

	public SocialRelationId(int loginInfoId, int socialLoginTypeId) {
		this.loginInfoId = loginInfoId;
		this.socialLoginTypeId = socialLoginTypeId;
	}

	@Column(name = "loginInfo_id", nullable = false)
	public int getLoginInfoId() {
		return this.loginInfoId;
	}

	public void setLoginInfoId(int loginInfoId) {
		this.loginInfoId = loginInfoId;
	}

	@Column(name = "socialLoginType_id", nullable = false)
	public int getSocialLoginTypeId() {
		return this.socialLoginTypeId;
	}

	public void setSocialLoginTypeId(int socialLoginTypeId) {
		this.socialLoginTypeId = socialLoginTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SocialRelationId))
			return false;
		SocialRelationId castOther = (SocialRelationId) other;

		return (this.getLoginInfoId() == castOther.getLoginInfoId())
				&& (this.getSocialLoginTypeId() == castOther
						.getSocialLoginTypeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLoginInfoId();
		result = 37 * result + this.getSocialLoginTypeId();
		return result;
	}

}
