package cn.sotou.dao.model;

// Generated 2014-2-25 20:52:59 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SocialRelation generated by hbm2java
 */
@Entity
@Table(name = "socialRelation", catalog = "sotou")
public class SocialRelation implements java.io.Serializable {

	private SocialRelationId id;
	private String socialId;

	public SocialRelation() {
	}

	public SocialRelation(SocialRelationId id, String socialId) {
		this.id = id;
		this.socialId = socialId;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "loginInfoId", column = @Column(name = "loginInfo_id", nullable = false)),
			@AttributeOverride(name = "socialLoginTypeId", column = @Column(name = "socialLoginType_id", nullable = false)) })
	public SocialRelationId getId() {
		return this.id;
	}

	public void setId(SocialRelationId id) {
		this.id = id;
	}

	@Column(name = "socialId", nullable = false, length = 32)
	public String getSocialId() {
		return this.socialId;
	}

	public void setSocialId(String socialId) {
		this.socialId = socialId;
	}

}
